name: Lint

on: [push, pull_request]

env:
  POETRY_VERSION: 1.1.13

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install "poetry==$POETRY_VERSION"
        poetry config virtualenvs.create false
        poetry install --no-root --no-interaction --no-ansi
    - name: Run lint 💅
      run: black graphene_federation --check
